title = "Custom Gitleaks Config"
[[rules]]
id = "hardcoded-secret"
description = "Detect hardcoded secrets or passwords"
regex = '''(?i)(secret[_-]?key|password)\s*=\s*["'][^"']+["']'''
tags = ["key", "password", "custom"]


# Google API key
[[rules]]
id = "google-api-key"
description = "Google API key (starts with AiZa)"
regex = '''(?i)(AIza[0-9A-Za-z\-_]{30,40})'''
tags = ["key","google","api"]
